# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/arm_timer/arm_timer.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_timer || ORIG_REF_NAME==arm_timer} -quiet] -quiet

# IP: bd/arm_timer/ip/arm_timer_processing_system7_0_0/arm_timer_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_timer_processing_system7_0_0 || ORIG_REF_NAME==arm_timer_processing_system7_0_0} -quiet] -quiet

# IP: bd/arm_timer/ip/arm_timer_axi_timer_0_0/arm_timer_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_timer_axi_timer_0_0 || ORIG_REF_NAME==arm_timer_axi_timer_0_0} -quiet] -quiet

# IP: bd/arm_timer/ip/arm_timer_ps7_0_axi_periph_0/arm_timer_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_timer_ps7_0_axi_periph_0 || ORIG_REF_NAME==arm_timer_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/arm_timer/ip/arm_timer_rst_ps7_0_100M_0/arm_timer_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_timer_rst_ps7_0_100M_0 || ORIG_REF_NAME==arm_timer_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/arm_timer/ip/arm_timer_auto_pc_0/arm_timer_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==arm_timer_auto_pc_0 || ORIG_REF_NAME==arm_timer_auto_pc_0} -quiet] -quiet

# XDC: bd/arm_timer/arm_timer_ooc.xdc
