# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_processing_system7_0_5/microblaze_arm_processing_system7_0_5.xci
# IP: The module: 'microblaze_arm_processing_system7_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_processing_system7_0_5/microblaze_arm_processing_system7_0_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_arm_processing_system7_0_5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_processing_system7_0_5/microblaze_arm_processing_system7_0_5.xci
# IP: The module: 'microblaze_arm_processing_system7_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_processing_system7_0_5/microblaze_arm_processing_system7_0_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_arm_processing_system7_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
