# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/microblaze_arm/microblaze_arm.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_arm || ORIG_REF_NAME==microblaze_arm} -quiet] -quiet

# IP: bd/microblaze_arm/ip/microblaze_arm_processing_system7_0_5/microblaze_arm_processing_system7_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_arm_processing_system7_0_5 || ORIG_REF_NAME==microblaze_arm_processing_system7_0_5} -quiet] -quiet

# IP: bd/microblaze_arm/ip/microblaze_arm_microblaze_0_5/microblaze_arm_microblaze_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_arm_microblaze_0_5 || ORIG_REF_NAME==microblaze_arm_microblaze_0_5} -quiet] -quiet

# IP: bd/microblaze_arm/ip/microblaze_arm_mdm_1_5/microblaze_arm_mdm_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_arm_mdm_1_5 || ORIG_REF_NAME==microblaze_arm_mdm_1_5} -quiet] -quiet

# IP: bd/microblaze_arm/ip/microblaze_arm_rst_ps7_0_50M_3/microblaze_arm_rst_ps7_0_50M_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_arm_rst_ps7_0_50M_3 || ORIG_REF_NAME==microblaze_arm_rst_ps7_0_50M_3} -quiet] -quiet

# IP: bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/microblaze_arm_axi_smc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_arm_axi_smc_2 || ORIG_REF_NAME==microblaze_arm_axi_smc_2} -quiet] -quiet

# IP: bd/microblaze_arm/ip/microblaze_arm_axi_mem_intercon_3/microblaze_arm_axi_mem_intercon_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_arm_axi_mem_intercon_3 || ORIG_REF_NAME==microblaze_arm_axi_mem_intercon_3} -quiet] -quiet

# IP: bd/microblaze_arm/ip/microblaze_arm_axi_timer_0_6/microblaze_arm_axi_timer_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_arm_axi_timer_0_6 || ORIG_REF_NAME==microblaze_arm_axi_timer_0_6} -quiet] -quiet

# IP: bd/microblaze_arm/ip/microblaze_arm_xbar_7/microblaze_arm_xbar_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_arm_xbar_7 || ORIG_REF_NAME==microblaze_arm_xbar_7} -quiet] -quiet

# IP: bd/microblaze_arm/ip/microblaze_arm_dlmb_v10_5/microblaze_arm_dlmb_v10_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_arm_dlmb_v10_5 || ORIG_REF_NAME==microblaze_arm_dlmb_v10_5} -quiet] -quiet

# IP: bd/microblaze_arm/ip/microblaze_arm_ilmb_v10_5/microblaze_arm_ilmb_v10_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_arm_ilmb_v10_5 || ORIG_REF_NAME==microblaze_arm_ilmb_v10_5} -quiet] -quiet

# IP: bd/microblaze_arm/ip/microblaze_arm_dlmb_bram_if_cntlr_5/microblaze_arm_dlmb_bram_if_cntlr_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_arm_dlmb_bram_if_cntlr_5 || ORIG_REF_NAME==microblaze_arm_dlmb_bram_if_cntlr_5} -quiet] -quiet

# IP: bd/microblaze_arm/ip/microblaze_arm_ilmb_bram_if_cntlr_5/microblaze_arm_ilmb_bram_if_cntlr_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_arm_ilmb_bram_if_cntlr_5 || ORIG_REF_NAME==microblaze_arm_ilmb_bram_if_cntlr_5} -quiet] -quiet

# IP: bd/microblaze_arm/ip/microblaze_arm_lmb_bram_5/microblaze_arm_lmb_bram_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_arm_lmb_bram_5 || ORIG_REF_NAME==microblaze_arm_lmb_bram_5} -quiet] -quiet

# IP: bd/microblaze_arm/ip/microblaze_arm_auto_pc_0/microblaze_arm_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_arm_auto_pc_0 || ORIG_REF_NAME==microblaze_arm_auto_pc_0} -quiet] -quiet

# XDC: bd/microblaze_arm/microblaze_arm_ooc.xdc
