# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/fabian/vivado/hardware_arm_only/hardware_arm_only.srcs/sources_1/bd/arm_timer/ip/arm_timer_axi_timer_0_0/arm_timer_axi_timer_0_0.xci
# IP: The module: 'arm_timer_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fabian/vivado/hardware_arm_only/hardware_arm_only.srcs/sources_1/bd/arm_timer/ip/arm_timer_axi_timer_0_0/arm_timer_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_timer_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/fabian/vivado/hardware_arm_only/hardware_arm_only.srcs/sources_1/bd/arm_timer/ip/arm_timer_axi_timer_0_0/arm_timer_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_timer_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/fabian/vivado/hardware_arm_only/hardware_arm_only.srcs/sources_1/bd/arm_timer/ip/arm_timer_axi_timer_0_0/arm_timer_axi_timer_0_0.xci
# IP: The module: 'arm_timer_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/fabian/vivado/hardware_arm_only/hardware_arm_only.srcs/sources_1/bd/arm_timer/ip/arm_timer_axi_timer_0_0/arm_timer_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_timer_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/fabian/vivado/hardware_arm_only/hardware_arm_only.srcs/sources_1/bd/arm_timer/ip/arm_timer_axi_timer_0_0/arm_timer_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'arm_timer_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
