# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.cache/wt [current_project]
set_property parent.project_path /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.4 [current_project]
set_property ip_output_repo /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/hdl/microblaze_arm_wrapper.vhd
add_files /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/microblaze_arm.bd
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_processing_system7_0_5/microblaze_arm_processing_system7_0_5.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_microblaze_0_5/microblaze_arm_microblaze_0_5.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_microblaze_0_5/microblaze_arm_microblaze_0_5_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_microblaze_0_5/microblaze_arm_microblaze_0_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_mdm_1_5/microblaze_arm_mdm_1_5.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_mdm_1_5/microblaze_arm_mdm_1_5_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_rst_ps7_0_50M_3/microblaze_arm_rst_ps7_0_50M_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_rst_ps7_0_50M_3/microblaze_arm_rst_ps7_0_50M_3.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_rst_ps7_0_50M_3/microblaze_arm_rst_ps7_0_50M_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_10/bd_5a27_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_19/bd_5a27_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_22/bd_5a27_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_23/bd_5a27_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_24/bd_5a27_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_25/bd_5a27_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_26/bd_5a27_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_27/bd_5a27_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_20/bd_5a27_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_21/bd_5a27_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_11/bd_5a27_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_12/bd_5a27_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_13/bd_5a27_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_14/bd_5a27_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_15/bd_5a27_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_2/bd_5a27_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_3/bd_5a27_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_4/bd_5a27_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_5/bd_5a27_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_6/bd_5a27_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_1/bd_5a27_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/bd_0/ip/ip_1/bd_5a27_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_smc_2/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_timer_0_6/microblaze_arm_axi_timer_0_6.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_axi_timer_0_6/microblaze_arm_axi_timer_0_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_xbar_7/microblaze_arm_xbar_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_dlmb_v10_5/microblaze_arm_dlmb_v10_5.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_dlmb_v10_5/microblaze_arm_dlmb_v10_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_ilmb_v10_5/microblaze_arm_ilmb_v10_5.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_ilmb_v10_5/microblaze_arm_ilmb_v10_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_dlmb_bram_if_cntlr_5/microblaze_arm_dlmb_bram_if_cntlr_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_ilmb_bram_if_cntlr_5/microblaze_arm_ilmb_bram_if_cntlr_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_lmb_bram_5/microblaze_arm_lmb_bram_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/ip/microblaze_arm_auto_pc_0/microblaze_arm_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/fabian/Documents/ensta/deuxieme/rob307/rob_307/hardware_model/hw_arm_microblaze/hw_arm_microblaze.srcs/sources_1/bd/microblaze_arm/microblaze_arm_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top microblaze_arm_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef microblaze_arm_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file microblaze_arm_wrapper_utilization_synth.rpt -pb microblaze_arm_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
